version: 2
sphinx:
  configuration: src/tests/system/docs/conf.py
python:
  install:
  - requirements: src/tests/system/docs/requirements.txt
build:
  os: ubuntu-22.04
  apt_packages:
  - libldap2-dev
  - libsasl2-dev
  - libssl-dev
  - python3-dev
  tools:
    python: '3.11'
formats: []
