name: Build SSSD's source rpm
inputs:
  version:
    description: Package version.
    required: true
  release:
    description: Package release.
    required: false
    default: '${{ github.run_number }}'
  working-directory:
    description: Working directory.
    required: false
    default: '.'
outputs:
  file:
    description: Source rpm file name.
    value: ${{ steps.srpm.outputs.file }}
  path:
    description: Path to the source rpm.
    value: ${{ steps.srpm.outputs.path }}
runs:
  using: 'composite'
  steps:
  # '-' is an illegal character for RPM version tag
  - name: Sanitize version
    id: sanitize
    shell: bash
    run: |
      version="$(echo ${{ inputs.version }} | sed 's/-/_/g')"
      echo "version=$version" >> $GITHUB_OUTPUT

  - name: Generate tarball and spec file
    shell: bash
    run: |
      pushd '${{ inputs.working-directory }}'
      release="${{ inputs.release }}"
      name="sssd-${{ steps.sanitize.outputs.version }}"
      tar -cvzf "$name.tar.gz" --transform "s,^,$name/," *

      cp contrib/sssd.spec.in ./sssd.spec

      sed -iE "s/@PACKAGE_NAME@/sssd/g" ./sssd.spec
      sed -iE "s/@PACKAGE_VERSION@/${{ steps.sanitize.outputs.version }}/g" ./sssd.spec
      sed -iE "s/@PRERELEASE_VERSION@/$release/g" ./sssd.spec
      popd
  - name: Build source rpm
    id: srpm
    uses: next-actions/build-srpm@master
    with:
      tarball: ${{ inputs.working-directory }}/sssd-${{ steps.sanitize.outputs.version }}.tar.gz
      specfile: ${{ inputs.working-directory }}/sssd.spec
      sourcefiles: ${{ inputs.working-directory }}/contrib/sssd.sysusers
