/*
    Generated by sbus code generator

    Copyright (C) 2017 Red Hat

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef _SBUS_SSS_CLIENT_PROPERTIES_H_
#define _SBUS_SSS_CLIENT_PROPERTIES_H_

#include <stdint.h>
#include <stdbool.h>

#include "sss_iface/sss_iface_types.h"

struct sbus_all_service {
    struct {
        bool is_set;
        uint32_t value;
    } debug_level;
};

#endif /* _SBUS_SSS_CLIENT_PROPERTIES_H_ */
