/*
    Generated by sbus code generator

    Copyright (C) 2017 Red Hat

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <errno.h>
#include <talloc.h>
#include <dbus/dbus.h>

#include "sbus/sbus_sync.h"
#include "sbus/sbus_sync_private.h"
#include "sbus/sbus_message.h"
#include "sbus/interface/sbus_iterator_readers.h"
#include "sbus/interface_dbus/sbus_dbus_client_sync.h"
#include "sss_iface/sbus_sss_arguments.h"
#include "sss_iface/sbus_sss_client_properties.h"

static errno_t
sbus_method_in__out_
    (struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method)
{
    TALLOC_CTX *tmp_ctx;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }


    ret = sbus_sync_call_method(tmp_ctx, conn, NULL, NULL,
                                bus, path, iface, method, NULL, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_pam_data_out_pam_response
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     struct pam_data * arg0,
     struct pam_data ** _arg0)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_pam_data in;
    struct _sbus_sss_invoker_args_pam_response *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_pam_response);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_pam_data,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_pam_response, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = talloc_steal(mem_ctx, out->arg0);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_raw_out_qus
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     DBusMessage *raw_message,
     uint16_t* _arg0,
     uint32_t* _arg1,
     const char ** _arg2)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_qus *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_qus);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }


    ret = sbus_sync_call_method(tmp_ctx, conn, raw_message, NULL, NULL,
                                dbus_message_get_path(raw_message),
                                dbus_message_get_interface(raw_message),
                                dbus_message_get_member(raw_message),
                                NULL, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_qus, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = out->arg0;
    *_arg1 = out->arg1;
    *_arg2 = talloc_steal(mem_ctx, out->arg2);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_s_out_
    (struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     const char * arg0)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_s in;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    in.arg0 = arg0;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_s,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_s_out_as
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     const char * arg0,
     const char *** _arg0)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_s in;
    struct _sbus_sss_invoker_args_as *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_as);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_s,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_as, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = talloc_steal(mem_ctx, out->arg0);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_s_out_b
    (struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     const char * arg0,
     bool* _arg0)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_s in;
    struct _sbus_sss_invoker_args_b *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_b);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_s,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_b, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = out->arg0;

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_s_out_qus
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     const char * arg0,
     uint16_t* _arg0,
     uint32_t* _arg1,
     const char ** _arg2)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_s in;
    struct _sbus_sss_invoker_args_qus *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_qus);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_s,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_qus, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = out->arg0;
    *_arg1 = out->arg1;
    *_arg2 = talloc_steal(mem_ctx, out->arg2);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_s_out_s
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     const char * arg0,
     const char ** _arg0)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_s in;
    struct _sbus_sss_invoker_args_s *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_s);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_s,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_s, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = talloc_steal(mem_ctx, out->arg0);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_sqq_out_q
    (struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     const char * arg0,
     uint16_t arg1,
     uint16_t arg2,
     uint16_t* _arg0)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_sqq in;
    struct _sbus_sss_invoker_args_q *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_q);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;
    in.arg1 = arg1;
    in.arg2 = arg2;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_sqq,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_q, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = out->arg0;

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_ss_out_o
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     const char * arg0,
     const char * arg1,
     const char ** _arg0)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_ss in;
    struct _sbus_sss_invoker_args_o *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_o);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;
    in.arg1 = arg1;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_ss,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_o, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = talloc_steal(mem_ctx, out->arg0);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_ssau_out_
    (struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     const char * arg0,
     const char * arg1,
     uint32_t * arg2)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_ssau in;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    in.arg0 = arg0;
    in.arg1 = arg1;
    in.arg2 = arg2;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_ssau,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_u_out_
    (struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     uint32_t arg0)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_u in;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    in.arg0 = arg0;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_u,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_us_out_qus
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     uint32_t arg0,
     const char * arg1,
     uint16_t* _arg0,
     uint32_t* _arg1,
     const char ** _arg2)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_us in;
    struct _sbus_sss_invoker_args_qus *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_qus);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;
    in.arg1 = arg1;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_us,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_qus, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = out->arg0;
    *_arg1 = out->arg1;
    *_arg2 = talloc_steal(mem_ctx, out->arg2);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_usq_out_
    (struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     uint32_t arg0,
     const char * arg1,
     uint16_t arg2)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_usq in;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    in.arg0 = arg0;
    in.arg1 = arg1;
    in.arg2 = arg2;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_usq,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_uss_out_qus
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     uint32_t arg0,
     const char * arg1,
     const char * arg2,
     uint16_t* _arg0,
     uint32_t* _arg1,
     const char ** _arg2)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_uss in;
    struct _sbus_sss_invoker_args_qus *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_qus);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;
    in.arg1 = arg1;
    in.arg2 = arg2;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_uss,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_qus, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = out->arg0;
    *_arg1 = out->arg1;
    *_arg2 = talloc_steal(mem_ctx, out->arg2);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

static errno_t
sbus_method_in_uusss_out_qus
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *bus,
     const char *path,
     const char *iface,
     const char *method,
     uint32_t arg0,
     uint32_t arg1,
     const char * arg2,
     const char * arg3,
     const char * arg4,
     uint16_t* _arg0,
     uint32_t* _arg1,
     const char ** _arg2)
{
    TALLOC_CTX *tmp_ctx;
    struct _sbus_sss_invoker_args_uusss in;
    struct _sbus_sss_invoker_args_qus *out;
    DBusMessage *reply;
    errno_t ret;

    tmp_ctx = talloc_new(NULL);
    if (tmp_ctx == NULL) {
        DEBUG(SSSDBG_FATAL_FAILURE, "Out of memory!\n");
        return ENOMEM;
    }

    out = talloc_zero(tmp_ctx, struct _sbus_sss_invoker_args_qus);
    if (out == NULL) {
        DEBUG(SSSDBG_CRIT_FAILURE,
              "Unable to allocate space for output parameters!\n");
        ret = ENOMEM;
        goto done;
    }

    in.arg0 = arg0;
    in.arg1 = arg1;
    in.arg2 = arg2;
    in.arg3 = arg3;
    in.arg4 = arg4;

    ret = sbus_sync_call_method(tmp_ctx, conn, NULL,
                                (sbus_invoker_writer_fn)_sbus_sss_invoker_write_uusss,
                                bus, path, iface, method, &in, &reply);
    if (ret != EOK) {
        goto done;
    }

    ret = sbus_read_output(out, reply, (sbus_invoker_reader_fn)_sbus_sss_invoker_read_qus, out);
    if (ret != EOK) {
        goto done;
    }

    *_arg0 = out->arg0;
    *_arg1 = out->arg1;
    *_arg2 = talloc_steal(mem_ctx, out->arg2);

    ret = EOK;

done:
    talloc_free(tmp_ctx);

    return ret;
}

errno_t
sbus_call_fleet_ProcessSSSDFiles
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     uint32_t arg_uid,
     const char * arg_user_dir,
     uint16_t arg_prio)
{
     return sbus_method_in_usq_out_(conn,
          busname, object_path, "org.freedesktop.FleetCommanderClient", "ProcessSSSDFiles", arg_uid, arg_user_dir, arg_prio);
}

errno_t
sbus_call_systemd_RestartUnit
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_name,
     const char * arg_mode,
     const char ** _arg_job)
{
     return sbus_method_in_ss_out_o(mem_ctx, conn,
          busname, object_path, "org.freedesktop.systemd1.Manager", "RestartUnit", arg_name, arg_mode,
          _arg_job);
}

errno_t
sbus_call_systemd_StartUnit
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_name,
     const char * arg_mode,
     const char ** _arg_job)
{
     return sbus_method_in_ss_out_o(mem_ctx, conn,
          busname, object_path, "org.freedesktop.systemd1.Manager", "StartUnit", arg_name, arg_mode,
          _arg_job);
}

errno_t
sbus_call_systemd_StopUnit
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_name,
     const char * arg_mode,
     const char ** _arg_job)
{
     return sbus_method_in_ss_out_o(mem_ctx, conn,
          busname, object_path, "org.freedesktop.systemd1.Manager", "StopUnit", arg_name, arg_mode,
          _arg_job);
}

errno_t
sbus_call_dp_access_RefreshRules
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.DataProvider.AccessControl", "RefreshRules");
}

errno_t
sbus_call_dp_backend_IsOnline
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_domain_name,
     bool* _arg_status)
{
     return sbus_method_in_s_out_b(conn,
          busname, object_path, "sssd.DataProvider.Backend", "IsOnline", arg_domain_name,
          _arg_status);
}

errno_t
sbus_call_dp_client_Register
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_Name)
{
     return sbus_method_in_s_out_(conn,
          busname, object_path, "sssd.DataProvider.Client", "Register", arg_Name);
}

errno_t
sbus_call_dp_failover_ActiveServer
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_service_name,
     const char ** _arg_server)
{
     return sbus_method_in_s_out_s(mem_ctx, conn,
          busname, object_path, "sssd.DataProvider.Failover", "ActiveServer", arg_service_name,
          _arg_server);
}

errno_t
sbus_call_dp_failover_ListServers
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_service_name,
     const char *** _arg_servers)
{
     return sbus_method_in_s_out_as(mem_ctx, conn,
          busname, object_path, "sssd.DataProvider.Failover", "ListServers", arg_service_name,
          _arg_servers);
}

errno_t
sbus_call_dp_failover_ListServices
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_domain_name,
     const char *** _arg_services)
{
     return sbus_method_in_s_out_as(mem_ctx, conn,
          busname, object_path, "sssd.DataProvider.Failover", "ListServices", arg_domain_name,
          _arg_services);
}

errno_t
sbus_call_proxy_auth_PAM
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     struct pam_data * arg_pam_data,
     struct pam_data ** _arg_pam_response)
{
     return sbus_method_in_pam_data_out_pam_response(mem_ctx, conn,
          busname, object_path, "sssd.ProxyChild.Auth", "PAM", arg_pam_data,
          _arg_pam_response);
}

errno_t
sbus_call_proxy_client_Register
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     uint32_t arg_ID)
{
     return sbus_method_in_u_out_(conn,
          busname, object_path, "sssd.ProxyChild.Client", "Register", arg_ID);
}

errno_t
sbus_call_resp_domain_SetActive
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_name)
{
     return sbus_method_in_s_out_(conn,
          busname, object_path, "sssd.Responder.Domain", "SetActive", arg_name);
}

errno_t
sbus_call_resp_domain_SetInconsistent
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_name)
{
     return sbus_method_in_s_out_(conn,
          busname, object_path, "sssd.Responder.Domain", "SetInconsistent", arg_name);
}

errno_t
sbus_call_resp_negcache_ResetGroups
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.Responder.NegativeCache", "ResetGroups");
}

errno_t
sbus_call_resp_negcache_ResetUsers
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.Responder.NegativeCache", "ResetUsers");
}

errno_t
sbus_call_dp_dp_autofsHandler
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     uint32_t arg_dp_flags,
     const char * arg_mapname,
     uint16_t* _arg_dp_error,
     uint32_t* _arg_error,
     const char ** _arg_error_message)
{
     return sbus_method_in_us_out_qus(mem_ctx, conn,
          busname, object_path, "sssd.dataprovider", "autofsHandler", arg_dp_flags, arg_mapname,
          _arg_dp_error,
          _arg_error,
          _arg_error_message);
}

errno_t
sbus_call_dp_dp_getAccountDomain
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     uint32_t arg_entry_type,
     const char * arg_filter,
     uint16_t* _arg_dp_error,
     uint32_t* _arg_error,
     const char ** _arg_domain_name)
{
     return sbus_method_in_us_out_qus(mem_ctx, conn,
          busname, object_path, "sssd.dataprovider", "getAccountDomain", arg_entry_type, arg_filter,
          _arg_dp_error,
          _arg_error,
          _arg_domain_name);
}

errno_t
sbus_call_dp_dp_getAccountInfo
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     uint32_t arg_dp_flags,
     uint32_t arg_entry_type,
     const char * arg_filter,
     const char * arg_domain,
     const char * arg_extra,
     uint16_t* _arg_dp_error,
     uint32_t* _arg_error,
     const char ** _arg_error_message)
{
     return sbus_method_in_uusss_out_qus(mem_ctx, conn,
          busname, object_path, "sssd.dataprovider", "getAccountInfo", arg_dp_flags, arg_entry_type, arg_filter, arg_domain, arg_extra,
          _arg_dp_error,
          _arg_error,
          _arg_error_message);
}

errno_t
sbus_call_dp_dp_getDomains
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_domain_hint,
     uint16_t* _arg_dp_error,
     uint32_t* _arg_error,
     const char ** _arg_error_message)
{
     return sbus_method_in_s_out_qus(mem_ctx, conn,
          busname, object_path, "sssd.dataprovider", "getDomains", arg_domain_hint,
          _arg_dp_error,
          _arg_error,
          _arg_error_message);
}

errno_t
sbus_call_dp_dp_hostHandler
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     uint32_t arg_dp_flags,
     const char * arg_name,
     const char * arg_alias,
     uint16_t* _arg_dp_error,
     uint32_t* _arg_error,
     const char ** _arg_error_message)
{
     return sbus_method_in_uss_out_qus(mem_ctx, conn,
          busname, object_path, "sssd.dataprovider", "hostHandler", arg_dp_flags, arg_name, arg_alias,
          _arg_dp_error,
          _arg_error,
          _arg_error_message);
}

errno_t
sbus_call_dp_dp_pamHandler
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     struct pam_data * arg_pam_data,
     struct pam_data ** _arg_pam_response)
{
     return sbus_method_in_pam_data_out_pam_response(mem_ctx, conn,
          busname, object_path, "sssd.dataprovider", "pamHandler", arg_pam_data,
          _arg_pam_response);
}

errno_t
sbus_call_dp_dp_sudoHandler
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     DBusMessage *raw_message,
     uint16_t* _arg_dp_error,
     uint32_t* _arg_error,
     const char ** _arg_error_message)
{
     return sbus_method_in_raw_out_qus(mem_ctx, conn,
          raw_message,
          _arg_dp_error,
          _arg_error,
          _arg_error_message);
}

errno_t
sbus_call_monitor_RegisterService
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_name,
     uint16_t arg_version,
     uint16_t arg_type,
     uint16_t* _arg_monitor_version)
{
     return sbus_method_in_sqq_out_q(conn,
          busname, object_path, "sssd.monitor", "RegisterService", arg_name, arg_version, arg_type,
          _arg_monitor_version);
}

errno_t
sbus_call_nss_memcache_InvalidateAllGroups
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.nss.MemoryCache", "InvalidateAllGroups");
}

errno_t
sbus_call_nss_memcache_InvalidateAllInitgroups
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.nss.MemoryCache", "InvalidateAllInitgroups");
}

errno_t
sbus_call_nss_memcache_InvalidateAllUsers
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.nss.MemoryCache", "InvalidateAllUsers");
}

errno_t
sbus_call_nss_memcache_InvalidateGroupById
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     uint32_t arg_gid)
{
     return sbus_method_in_u_out_(conn,
          busname, object_path, "sssd.nss.MemoryCache", "InvalidateGroupById", arg_gid);
}

errno_t
sbus_call_nss_memcache_UpdateInitgroups
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_user,
     const char * arg_domain,
     uint32_t * arg_groups)
{
     return sbus_method_in_ssau_out_(conn,
          busname, object_path, "sssd.nss.MemoryCache", "UpdateInitgroups", arg_user, arg_domain, arg_groups);
}

errno_t
sbus_call_service_clearEnumCache
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.service", "clearEnumCache");
}

errno_t
sbus_call_service_clearMemcache
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.service", "clearMemcache");
}

errno_t
sbus_call_service_goOffline
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.service", "goOffline");
}

errno_t
sbus_call_service_resInit
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.service", "resInit");
}

errno_t
sbus_call_service_resetOffline
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.service", "resetOffline");
}

errno_t
sbus_call_service_rotateLogs
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.service", "rotateLogs");
}

errno_t
sbus_call_service_sysbusReconnect
    (struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path)
{
     return sbus_method_in__out_(conn,
          busname, object_path, "sssd.service", "sysbusReconnect");
}

