[sssd]
services = nss, pam
domains = shadowutils

[nss]
# A comma-separated list of users who are not allowed to log in.
# filter_users = user1, user2
# A comma-separated list of groups, members of which are not allowed to log in.
# filter_groups = group1, group2
#
# Override the home directory of users with the value of this option.
# override_homedir = /home/%u
# If the user has no home directory defined in the identity provider, use the
# value of this option.
# fallback_homedir = /home/%u
#
# Override the shell of users with the value of this option.
# override_shell = /bin/bash
# If the user's shell is not in /etc/shells, use the value of this option.
# shell_fallback = /bin/bash
# If the user has no shell defined, use the value of this option.
# default_shell = /bin/bash
# A comma-separated list of shells. Users having a shell from this list will
# be denied access.
# vetoed_shells = /bin/csh, /bin/tcsh

[pam]

[domain/shadowutils]
id_provider = proxy
proxy_lib_name = files

auth_provider = proxy
proxy_pam_target = sssd-shadowutils

proxy_fast_alias = True
