/*
    Generated by sbus code generator

    Copyright (C) 2017 Red Hat

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef _SBUS_DBUS_CLIENT_SYNC_H_
#define _SBUS_DBUS_CLIENT_SYNC_H_

#include <errno.h>
#include <talloc.h>
#include <tevent.h>

#include "sbus/sbus_sync.h"
#include "sbus/interface_dbus/sbus_dbus_client_properties.h"

errno_t
sbus_call_DBusProperties_Get
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_interface_name,
     const char * arg_property_name,
     DBusMessage **_reply);

errno_t
sbus_call_DBusProperties_GetAll
    (TALLOC_CTX *mem_ctx,
     struct sbus_sync_connection *conn,
     const char *busname,
     const char *object_path,
     const char * arg_interface_name,
     DBusMessage **_reply);

errno_t
sbus_call_DBusProperties_Set
    (struct sbus_sync_connection *conn,
     DBusMessage *raw_message);

#endif /* _SBUS_DBUS_CLIENT_SYNC_H_ */
