name: "ci"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/sssd/ci-client-devel:latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      id: dependencies
      uses: ./.github/actions/install-dependencies

    - name: Configure sssd
      uses: ./.github/actions/configure

    - name: make
      shell: bash
      working-directory: x86_64
      run: |
        source ../contrib/fedora/bashrc_sssd
        make CFLAGS+="$SSS_WARNINGS -Werror"

    - name: make check
      shell: bash
      working-directory: x86_64
      run: |
        source ../contrib/fedora/bashrc_sssd
        make CFLAGS+="$SSS_WARNINGS -Werror" check

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build
        path: |
          x86_64/config.log
          x86_64/config.h
          x86_64/test-suite.log
        if-no-files-found: ignore

  result:
    name: All tests are successful
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Fail on failure
        if: |
          needs.build.result != 'success'
        run: exit 1
